### ISSUE TITLE
Add a field that can be a discriminate for Ok / Err

### ISSUE THREAD

**Issue by kofno** [kofno/resulty#1]
This will allow type guards to be used to discriminate between Ok and and Err responses. `cata` serves this same purpose, but it is heavily generic, and is often confusing (for users, and also for typescript, apparently). Falling back to type guards might make the library more palatable.

**Comment by arnauorriols** [comment]
Has this been implemented? I'd appreciate such improvement.

**Comment by kofno** [comment]
No. I ended up closing this because, in practice, I've found that `cata` or some combination of `map`, `andThen`, `getOrElse`, or `getOrelseValue` have covered all my cases. And typescript has improved since I opened this ticket.
